# Generated by Django 4.2.21 on 2025-05-20 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0002_question_question_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.PositiveSmallIntegerField(unique=True, verbose_name='Số Cấp độ')),
                ('level_name', models.CharField(max_length=100, unique=True, verbose_name='Tên Cấp độ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả Cấp độ')),
            ],
            options={
                'verbose_name': 'Cấp độ',
                'verbose_name_plural': 'Các Cấp độ',
                'ordering': ['level_number'],
            },
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['level__level_number', 'module__module_name', '-created_at'], 'verbose_name': 'Câu Hỏi', 'verbose_name_plural': 'Các Câu Hỏi'},
        ),
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz_api.level', verbose_name='Cấp độ'),
        ),
    ]
